apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-converter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KKamJi98/image-converter
    path: infra/helm-chart
    targetRevision: main
    helm:
      releaseName: image-converter
      valueFiles:
      - kkamji_values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: image-converter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
