apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  # annotations:
  #   notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-sync-failed.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-sync-running.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-deployed.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-health-degraded.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-health-progressing.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-health-healthy.slack: "argocd-alarm"
  #   notifications.argocd.io/subscribe.on-health-unknown.slack: "argocd-alarm"
spec:
  project: default
  source:
    repoURL: https://github.com/KKamJi98/helm-charts
    path: metrics-server
    targetRevision: main
    helm:
      releaseName: metrics-server
      valueFiles:
      - kkamji_values.yaml
        #      values: |-
        #        apiService:
        #          create: true
        #        args:
        #          - --kubelet-insecure-tls
        #          - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
