apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  labels:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/KKamJi98/helm-charts
    path: prometheus-thanos
    targetRevision: main
    helm:
      releaseName: thanos
      valueFiles:
        - kkamji_local_values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
